### ISSUE TITLE
Please check my comment below for review

### ISSUE THREAD

**Issue by Ambrosegithub** [HatimDev-HE/Trials-2#2]
## Changes required.

- [ ]  make your readme more descriptive to make your  project more professional

**Comment by elfin-git** [comment]
@HatimDev-HE  Please put your tribute info and your image in a section tag

**Comment by Ambrosegithub** [comment]
- [ ] [11](https://github.com/HatimDev-HE/Trials-2/blob/fc3850ff5d7efcbfcd22a46a1e9a530cf6a33ca5/index.html#L11) make use of HTML5semantic tag intstead of div to make your code look professional and clean
